### ISSUE TITLE
[ERROR] Failed binding IPv4 listening socket: Permission denied (13)

### ISSUE THREAD

**Issue by dpodhorsky** [kahopoon/Pokemon-Go-Controller#10]
Running the Controller in xCode on a iPhone Simulator, get the above error code when starting debugging.

**Comment by kahopoon** [comment]
@dpodhorsky you should run it on a real device in order to get a ip to make the embedded server works as the simulator is a sandbox :)

**Comment by Omeryl** [comment]
@kahopoon it will work on the simulator, they just need to use a port above 1024 ;)

**Comment by kahopoon** [comment]
@Omeryl love ya ~3~

**Comment by dpodhorsky** [comment]
@kahopoon , @Omeryl Thanks! I was able to get around that issue!

**Comment by puttichan** [comment]
@dpodhorsky I was wondering if you could upload a tutorial for this?
