### ISSUE TITLE
generateXML can't update the gpx file

### ISSUE THREAD

**Issue by mingsnu** [kahopoon/Pokemon-Go-Controller#12]
First of all thank you for sharing the code!
I found that I can't update the `pokemonLocation.gpx` file while running the `generateXML` function. Any idea what's happening there?
Thank you!

**Comment by nazimamin** [comment]
what error are you getting? It works for me and should be overwriting the previous value on every call to the func

**Comment by mingsnu** [comment]
Yes, you are right. It wasn't the problem after I check it carefully. I found my `PokemonHandler` can not load the `pokemonLocation.gpx` file automatically when it is updated. It stick to the initial position where the controller starts. I guess it must be very easy to fix, but I don't know how. I might never learn xcode if not playing Pokemon, you know...

**Comment by nazimamin** [comment]
right click on PokemonHandler folder -> Add Files to PokeMonHandler -> choose your file.

**Comment by kahopoon** [comment]
@mingsnu remember when you import your file make sure 'copy if needed' option is unchecked, import by reference :)

**Comment by mingsnu** [comment]
@kahopoon Yes, I didn't check the 'copy if needed' option.
@NazimAmin I followed your instruction but still doesn't work. I have to keep clicking the `pokemonLocation` to update my location in PokemonGo. 
![sc](http://i.imgur.com/6xs16N7.png?1)
Thank you all for your help!

**Comment by mingsnu** [comment]
Sorry, I made a stupid mistake. I forgot to run the auto-click script.
Sorry again for the trouble.

**Comment by g3crossfire** [comment]
how did you get the gpx file and how did you make if work? step by step please :)
