### ISSUE TITLE
'CGPostMouseEvent' is deprecated

### ISSUE THREAD

**Issue by pawin** [kahopoon/Pokemon-Go-Controller#17]
running on macOS Sierra got this warning: 'CGPostMouseEvent' is deprecated: first deprecated
      in OS X 10.6 [-Wdeprecated-declarations]

**Comment by kahopoon** [comment]
yes but you can still compile and run on Sierra beta 2 :), if looking for solution, please have a look on http://stackoverflow.com/questions/1483567/cgpostmouseevent-replacement-on-snow-leopard
