### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by g3crossfire** [kahopoon/Pokemon-Go-Controller#26]
I'm a noob. when i try to build this app i get this error... can you please help?

Check dependencies

Code Sign error: No matching provisioning profile found: Your build settings specify a provisioning profile with the UUID “net.kahopoon.PokemonController”, however, no such provisioning profile was found.

**Comment by devmustache** [comment]
change "kahopoon" string to anything you want. That name must be unique.

**Comment by g3crossfire** [comment]
So where do I go to change that?

**Comment by 5SMNOONMS5** [comment]
![image](https://cloud.githubusercontent.com/assets/8379901/16789272/b7322f28-48de-11e6-8847-c9eb1ce2a892.png)
change here

**Comment by g3crossfire** [comment]
So easy once you know..... Thanks for taking the time to help 👍
