### ISSUE TITLE
Catching Pokemon becomes impossible after using the controller for some time

### ISSUE THREAD

**Issue by niklas-sparfeld** [kahopoon/Pokemon-Go-Controller#27]
It seems to me, that after some time jetting around the world to "see other places", I cannot catch Pokemon anymore.

Each and every Pokemon you try to catch escapes you ball and runs away. Every single time.

Until this is further investigated, I would refrain from using the controller.

I hope that by tomorrow I will be able to play again.

**Comment by puttichan** [comment]
You are soft banned.
You will be unbanned after several hours.
It isnt technically because of this you are banned.
You just misused it to the point where the game detected you hacking.

**Comment by niklas-sparfeld** [comment]
I can confirm, that catching Pokemon works again in the morning.

Keep a low profile when using the controller ;)

**Comment by puttichan** [comment]
Hey could you possibly tell me how to do this? I am able to change location through the app, but it doesnt sync with the game...

**Comment by niklas-sparfeld** [comment]
Wow I was just writing a rant about people who just want an easy cheating tool, when I remembered: Don't feed the trolls :)

**Comment by puttichan** [comment]
Lmao jesus christ.
I am not asking for the whole process?
Nevermind, you are being an obvious asshole ㅗ^^ㅗ.
