### ISSUE TITLE
Hello kahopoon,i have a problem,would u tell me what can i do?

### ISSUE THREAD

**Issue by crazypoo** [kahopoon/Pokemon-Go-Controller#3]
[DEBUG] Connection received 180 bytes on socket 16
[DEBUG] Connection aborted with status code 500 on socket 16

**Comment by kahopoon** [comment]
as sometime the port 80 may consume by other app on your ipad/iphone, you may try different port for your game controller web server, at Xcode project's ViewController.swift, func startWebServer()

**Comment by crazypoo** [comment]
Ok, I will try the other port on my phone

**Comment by crazypoo** [comment]
@kahopoon I tried it,but is doesent work.Here is my Xcode crash image.When u see it ,u will know my problem.[http://m.weibo.cn/1734113321/3996379171088573?uicode=10000002&moduleID=feed&mid=3996379171088573&luicode=10000011&_status_id=3996379171088573&lfid=2304131734113321_-_WEIBO_SECOND_PROFILE_WEIBO&sourcetype=page&lcardid=](url)

**Comment by kahopoon** [comment]
@crazypoo I can't open that url, could you post the image here?

**Comment by crazypoo** [comment]
@kahopoon  Or would u tell me ur email address?my email address is dengjiehao8570724@hotmail.com .... So u can email me n I will post my problem image 4 u

**Comment by kahopoon** [comment]
did you get this work? my email: kahopoon@gmail.com
