### ISSUE TITLE
Build succeeded but nothing in my device.

### ISSUE THREAD

**Issue by ghost** [kahopoon/Pokemon-Go-Controller#33]
![img](http://ww3.sinaimg.cn/large/0060lm7Tgw1f5sb2sz8c9j30o508276k.jpg)

I am not a IOS developer,I have built this APP  succeeded in Xcode, but there is nothing be found  in my device. 

Is that I  did something wrong ? Can somebody point it out ?  Thanks

**Comment by puttichan** [comment]
Product -> Build For
