### ISSUE TITLE
Every Pokemon keep escaping from captures

### ISSUE THREAD

**Issue by AsakuraB** [kahopoon/Pokemon-Go-Controller#35]
I've been using this project to change my location from China to Sydney and New York catching pokemons. But after 2 days hard work and 100+ pokemons collection, it seems that I can't catch any more pokemons. Everytime I throw a pokeball to a pokemon, even those easiest ones, they escape at once.
I found a similar situation from http://gaming.stackexchange.com/questions/274044/why-do-pok%C3%A9mon-keep-escaping-from-captures .
Dose anyone else have same situation here? Or dose anyone know why this happens and what can I do?

**Comment by kwstasna** [comment]
Could you please tell us how to run the readAndChangeXML.py and create the pokemonLocation.gpx file please?

**Comment by puttichan** [comment]
You are soft banned.
Don't try to change your location from China to Sydney and New York.
The program automatically detects your GPS spoofing and you will be banned for a few hours.
If you wish to spoof it, log out, delete the Go, and spoof it first beforehand.

**Comment by AsakuraB** [comment]
@kwstasna just follow README.md step by step, it's pretty clear.

**Comment by AsakuraB** [comment]
@puttichan it turns out that some others have same situation with me once they move from one location to another too fast using GPS spoofing.

**Comment by puttichan** [comment]
@AsakuraB This is really common soft ban for people who are spoofing their GPS.
But who cares? You don't really get banned if you carefully use them.

**Comment by alexiscreuzot** [comment]
Pokestop seems unresponsive and pokemons keep getting away.  think they might have implemented a security feature to avoid GPS spoofing.

**Comment by alexiscreuzot** [comment]
Nothing is working anymore, I wonder if they did not implement a mechanism to ban spoofers :/

**Comment by neospio** [comment]
I am not able to see any Pokemon appear even I "stand" right in the middle of the circle. Tried for different places..I wonder this method can still working now...

**Comment by ysrotciv** [comment]
@neospio
This method is just to fake you location of your IOS device. The easiest way to test is seeing if your location in google map is same with your controller.

**Comment by jessedobbelaere** [comment]
You're soft-banned because you faked the gps data and made huge jumps from China to Sydney to New York: https://www.reddit.com/r/pokemongo/comments/4rtee1/massive_glitch_every_single_pokemon_runs_away/

I hope this only lasts a few hours ;) Maybe better to add this to the readme?

**Comment by neospio** [comment]
@ysrotciv This method DO faked my location to wherever I want in the world, I can even "walk" through different streets from US to Australia while I am sitting in front of my mac. But the pokemon just won't appear using this method.:(
![image](https://cloud.githubusercontent.com/assets/7780988/16826598/3fe79fd8-49b1-11e6-8572-62a7df3c3150.png)

**Comment by ysrotciv** [comment]
@neospio
I guess you're banned.

**Comment by AsakuraB** [comment]
@neospio it's just network problem. Wait for a minute and pokemons will appear.

For all,
I've been released from this "soft banned" after a few hours waiting.

For reference only,
I went offline from New York and get online in Sydney after 3-4 hours, no more soft banned happend. And Sydney is MUCH MORE bustling than New York, especially near the Opera House.
