### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by rlam3** [kahopoon/Pokemon-Go-Controller#4]
@kahopoon When you talk about your controller's ip. Is it the ipad controller in the gif ip? Or would it be the ip of computer which the xcode is running on? I tried both laptop and ipad ip and I keep getting refused connection.  Thanks
Is there a specific environment setting that you did to enable to connection? 

When I run the python script. It keeps giving me the following error:

[Errno 61] Connection refused

But when I try to use your ip 172.16.255.195. It shows it as timeout.

**Comment by Omeryl** [comment]
Hey,

It'd be whatever the IP of the device running the controller is (that is, the app with the up/down/left/right controls and the map).

**Comment by rlam3** [comment]
@Omeryl Does this process require me to get the developer account in order for this to work? Because I'm running the simulator via the laptop but it does't seem like the XML is generating even though I'm pointing the IP to the laptop. I'm pointing it to the inet ip correct?

I took a closer look at the code and it seems like there is some sort of permission needed to bind ipv4 address to some socket. Is there a way to enable this for simulators?

``` lldb
[ERROR] Failed binding IPv4 listening socket: Permission denied (13)
```

**Comment by OverlordQ** [comment]
You gunna get banned.

**Comment by notbdu** [comment]
@rlam3 because port 80? try starting the `GCDWebServer` on port 8080 or something. Ports below 1024 require superuser permissions

**Comment by kahopoon** [comment]
@rlam3 make sure your game controller (ipad/iphone) is connected with your own wifi to get a ip, in case of connection refused, the mot common case is that you opened the controller before you open the python script. I suggest you first open the python script first, the script will then telling you timeout as you haven't opened the controller, then when you open the controller, connection will be established. Or it will be the case that @bdupharm mentioned, it may be other application on your controller currently using 80 and you should change the port number too then :)

**Comment by rlam3** [comment]
@kahopoon Thanks! works wonders except just having difficulty with using the simulator and auto clicker in conjunction with the same environment haha

**Comment by notbdu** [comment]
@rlam3 I added another click event back onto the simulator after clicking the location => pokemonLocation dropdown on xcode. I also set some time to space out the location updates so I had time to move around.

Alternatively I dumped a list of coordinates to a file to simulate walking around the city. I then wrote a python script to read from that list and update the gpx file. Whatever works for you, once you get the basic concept there's many ways you can go about this.
