### ISSUE TITLE
Support for Xcode 8

### ISSUE THREAD

**Issue by anushkmittal** [kahopoon/Pokemon-Go-Controller#48]
I believe that majority of the users who would use this git are running iOS 10 either the Developer Preview or Public Beta. Support for Xcode 8 - Beta is essential to support the disk image of these devices.

**Comment by innocuoussoul** [comment]
in Build Settings set legacy swift language version to Yes and update the viewcontroller with this code: 
change rand() to arc4random()

func moveInterval() -> Double {
        return Double("0.0000(40 + (arc4random() % 20))")!

**Comment by iam4x** [comment]
I do support Xcode 8 in my similar app if you want to check out https://github.com/iam4x/pokemongo-webspoof
