### ISSUE TITLE
timeout when running .py script

### ISSUE THREAD

**Issue by whoyawn** [kahopoon/Pokemon-Go-Controller#55]
When I run the script after running the controller, my terminal keeps looping through "timeout" and no gpx file is generated. I'm using the ip address generated in the console of xcode when I run controller. I also tried running it without xcode and I still get a timeout. What does this mean?

**Comment by DevMike911** [comment]
Hi, just change the timeout from 1 to 5 seconds in both python scripts. I also I add a NSTimer after in the Pokemon Controller app with 4 seconds where the controller fire a new location. Now I can play this game over 1h with no errors :)

**Comment by sidan5** [comment]
Does it works with Xcode simulator as controller? I get the timeout messages even when set to 5 sec.

**Comment by ysrotciv** [comment]
this branch implement what you want
https://github.com/Lockeysama/Pokemon-Go-Controller
