### ISSUE TITLE
Need help with starting this?

### ISSUE THREAD

**Issue by puttichan** [kahopoon/Pokemon-Go-Controller#6]
I was wondering if anyone could tell me how to get started with this?
Like possibly a tutorial?
Thanks!

**Comment by kahopoon** [comment]
Hi @puttichan , which part you stuck with ? let me know first :p

**Comment by markcerqueira** [comment]
Steps in general are very confusing even for a developer. How about assuming someone is on a Mac with Xcode installed. What's the step-by-step instructions to get things running. It seems like I need to run the app from Xcode AND a web server?

**Comment by kahopoon** [comment]
@markcerqueira sure, I'll explain more on steps asa i can squeeze some time. At game controller, while you run it from xcode, you can left its own, and that app embedded with web server. And on other side, you create a blank project and run on your actual playing pokemon go device, and this device should connect with your xocde so as to constantly  change your game controller's location

**Comment by markcerqueira** [comment]
@kahopoon Ah I see! Maybe point out you need to run that server on a device or simulator I'm guessing?

**Comment by puttichan** [comment]
I can do the latter option where I create a blank project and run on my
actual playing pokemon go device! I just wanted to know step by step
tutorial.

Thanks a lot for responding to my request!

I really do appreciate it.

**Comment by kahopoon** [comment]
@markcerqueira @puttichan Bravo, thanks for the feedback :p

**Comment by puttichan** [comment]
If this helps to clarify....

I have Xcode ready (because I saw videos about Tommy Callaway (a youtuber
who uploaded tutorials on how to do simulated walking in Pokemon Go)). So
basically all I have knowledge about it is knowledge on those videos!

**Comment by brendanvu1** [comment]
So do both devices have to be connected to Xcode for this to work? I was able to load the game controller onto my iPad. I was also able to accomplish simulating a location on the pokemon go application, but the controller doesn't sync with the game. I have yet to complete the auto click terminal codes because I honestly get confused and I'm no sure which two buttons the ReadMe file was referring to.

**Comment by devmustache** [comment]
@brendanvu1 same here

**Comment by rlam3** [comment]
@puttichan  if youd like to learn how to program. apple docs are a good way to start.

**Comment by puttichan** [comment]
Made it until syncing two devices. Just need to autorun the buttons which should be easy enough.
