### ISSUE TITLE
Reverting back to true location

### ISSUE THREAD

**Issue by brandonmowat** [kahopoon/Pokemon-Go-Controller#60]
This is not the same issue as "Springing back to true location".

I wand my phone to use my actual location so I can still play the game as intended. However, I deleted the "PokemonHandler" from my phone and my phone still thinks I am in the middle of nowhere (the same initial location on the controller).

Any suggestions on how to fix my Location issues?

**Comment by brandonmowat** [comment]
I think I fixed it by deleting the app and turning my phone off and on again.

**Comment by brandonmowat** [comment]
No, it is not fixed...

**Comment by jessedobbelaere** [comment]
Maybe the location is calculated through a combination of gps data and cell phone triangulation (approximate location between cellphone antenna towers). I usually put on airplane mode to disable everything, but afterwards I enable only wifi.

**Comment by ffittschen** [comment]
@brandonmowat Did you turn the simulation off in Xcode while your phone is connected?
![screen shot 2016-07-18 at 01 10 35](https://cloud.githubusercontent.com/assets/7734806/16903664/a0f5c5c2-4c84-11e6-9c07-89514fea453a.png)

**Comment by jessedobbelaere** [comment]
I have the same issue actually. Airplane mode + wifi + simulate location stays on in xcode, but after a while, suddenly i'm back at my true location.

**Comment by ffittschen** [comment]
@jessedobbelaere This is not the same issue that @brandonmowat described.. He WANTS to have the true location. But you can take a look at #41

**Comment by JensDebergh** [comment]
A fresh restart of your device will always work!

**Comment by brandonmowat** [comment]
Thanks for all the help guys. It seems that eventually it will start picking up my location again. I'm not sure if it's time or if I end up doing something to trigger it. Closing issue...
