### ISSUE TITLE
no such module GCDWebServer

### ISSUE THREAD

**Issue by xSyrix** [kahopoon/Pokemon-Go-Controller#7]
@kahopoon would you please give me a hand how to solve this ?

when i tried to compile the project i am getting this error 

no such module GCDWebServer in the PockemonController > PockemonController > ViewController.swift 

import GCDWebServer

thank you in advance 

Cheers

**Comment by TylerHelmuth** [comment]
I'm experiencing the same issue.

**Comment by NazimAmin** [comment]
General -> add GCDWebServer.framework under Linked Frameworks and Libraries.

If you are on XCode 8, make sure you sign all the frameworks one by one

**Comment by BrandonGoo** [comment]
Tried to Assign but I was not able to find GCDWebServer.framework under Linked Frameworks and Libraries. 

I am on Version 7 of Xcode.

**Comment by xSyrix** [comment]
i added the GCDWebServer.framework, now i am getting this error 

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by NazimAmin** [comment]
Are you opening the project directly clicking on the PokemonControlle.XcodeProjr? If so, instead in Xcode File -> Open ->Select the whole folder Pokemon-Go-Controller-master

**Comment by xSyrix** [comment]
@NazimAmin, Thank you - i manage to to compile the project. now i need to figure out how to set it up to work with the phone & pokemon go.

is there a setup by step guide ?

Cheers

**Comment by NazimAmin** [comment]
Basically, just follow the readme. To make it short, Just use the .gpx file in Xcode and inside it, change the lan, lat. (You can get that from google maps) The mock the location.

**Comment by xSyrix** [comment]
i think i celebrated too fast. i am following the readme and here is my feedback and issue i face.

1) i manage to compile the project and run it on my iPad. i can see the pokeball and the control. but i am not able to see the maps.

2) i also modify the readAndChangeXML.py to add my iPad ip. than i run the py script and get the following error 

python ./readAndChangeXML.py 

  File "./readAndChangeXML.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file ./readAndChangeXML.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

thank in advance for the input

**Comment by NazimAmin** [comment]
if you run the app on your ipad/iphone your ip will looks something like http://iPhone.local/ for example.

**Comment by xSyrix** [comment]
Yes, that part is working.  i manage to get the ip like http://iPhone.local/

still getting these error 

File "./readAndChangeXML.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file ./readAndChangeXML.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Joeys-MacBook-Pro:Pokemon-Go-Controller-master joeychiang$ python ./readAndChangeXML.py 

and how do i fixed the maps ? i don't see the maps just bank screen with a pokeball

**Comment by xSyrix** [comment]
i figure out the Non-ASCII character '\xe2' in file issue. all you need to do is change the " to ' in this line 

From 
response = urllib2.urlopen("http://ThunderStorm.local/", timeout = 1)

to

response = urllib2.urlopen('http://ThunderStorm.local/', timeout = 1)

**Comment by kahopoon** [comment]
@NazimAmin many thanks:)

**Comment by xSyrix** [comment]
@NazimAmin, thank you for being patient with me .
