### ISSUE TITLE
GCDWebServer

### ISSUE THREAD

**Issue by BrandonGoo** [kahopoon/Pokemon-Go-Controller#8]
Working through the process:

Currently getting a Swift Complier Error - No such module "GCDWebServer" ViewController.swift

Launched from PokemonController.xcodeporj

Set IP for readAndChangeXML.py

GCDWebServer.framework has been added to Linked Frameworks and Libraries. 

Not sure what else I am missing or what else I need to do. Just trying to get this going :D Thanks for the help

**Comment by kahopoon** [comment]
please try to open the project using .xcworkspace instead of .xcodeproj :)

**Comment by nazimamin** [comment]
Make sure to sign it 👍

**Comment by BrandonGoo** [comment]
Thanks for the comments guy. Working on it but I think I am doing something wrong. I will check in with my co-workers tomorrow when I get in. They referred me to this :D

**Comment by abdelhakel** [comment]
how i do signing it ? i got this message : 
"Failed to code sign "PokemonController".
No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “net.kahopoon.PokemonController” were found.
Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles."

And then : 
"An App ID with Identifier 'net.kahopoon.PokemonController' is not available. Please enter a different string."
